# Generated by Django 2.1.7 on 2019-03-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
